apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: catalog
  name: catalog
spec:
  containers:
  - image: acr0demo0acr.azurecr.io/catalogapi:v2
    name: catalog
    envFrom:
    - secretRef:
        name: demo-secret
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
