apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi
  labels:
    deploy: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - image: "{{registry}}.azurecr.io/tripinsights/poi:1.0"
        imagePullPolicy: Always
        name: poi
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        - containerPort: 443
          name: https
          protocol: TCP
        env:
        - name: WEB_SERVER_BASE_URI
          value: 'http://0.0.0.0'
        - name: WEB_PORT
          value: '8080'
        - name: ASPNETCORE_ENVIRONMENT
          value: 'Production'
        envFrom:
        - secretRef:
            name: sql
---
apiVersion: v1
kind: Service
metadata:
  name: poi
spec:
  type: ClusterIP
  selector:
    app: poi
  ports:
  - protocol: TCP
    name: http
    port: 80
    targetPort: 80
  - protocol: TCP
    name: https
    port: 443
    targetPort: 443
